import { Footer, Header } from '@/component';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="relative ">
                <Header />
                <div className="mx-[230px]">{children}</div>
                <Footer />
            </body>
        </html>
    );
}
